artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/datasets/brijbhushannanda1979/bigmart-sales-data
  kaggle_file_path: .kaggle/kaggle.json
  test_filename: Test.csv
  train_filename: Train.csv

data_validation:
  root_dir: artifacts/data_validation
  schema_dir: configs/schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html

data_cleaning:
  root_dir: artifacts/data_cleaning
  clean_csv_dir: artifacts/data_cleaning/clean_data
  clean_train_filename: train.csv
  clean_validation_filename: validation.csv
  clean_test_filename: test.csv

data_transformation:
  root_dir: artifacts/data_transformation
  transform_dir: artifacts/data_transformation/transformed_data
  transform_train_filename: train
  transform_validation_filename: validation
  column_transformer_object: column_transformer.pkl

model_training:
  root_dir: artifacts/model_training
  experiment_runs_filename: mlflowruns

model_evaluation:
  root_dir: artifacts/model_evaluation
  base_accuracy: 0.56
  model_filename: model_evaluation.csv

model_pusher:
  dest_dir: application