columns:
    Item_Identifier: category
    Item_Weight: float
    Item_Fat_Content: category
    Item_Visibility: float
    Item_Type: category
    Item_MRP: float
    Outlet_Identifier: category
    Outlet_Establishment_Year: int64
    Outlet_Size: category
    Outlet_Location_Type: category
    Outlet_Type: category
    
 

numerical_columns: 
   Item_Weight  
   Item_Visibility  
   Item_MRP  
   Outlet_Establishment_Year
  
categorical_columns: 
    Item_Identifier
    Item_Fat_Content
    Item_Type
    Outlet_Identifier
    Outlet_Size
    Outlet_Location_Type
    Outlet_Type

min_of_column:
  Item_Weight: 4.555
  Outlet_Establishment_Year: 1985
  
 

max_of_column:
  Item_Weight: 21.35
  Outlet_Establishment_Year: 2009


target_column: Item_Outlet_Sales

domain_value:  
    Item_Type:
      - Baking Goods
      - Breads
      - Breakfast
      - Canned
      - Dairy
      - Frozen Foods
      - Fruits and Vegetables
      - Hard Drinks
      - Health and Hygiene
      - Household
      - Meat
      - Others
      - Seafood
      - Snack Foods
      - Soft Drinks
      - Starchy Foods

    Outlet_Identifier:
      - OUT010
      - OUT013
      - OUT017
      - OUT018
      - OUT019
      - OUT027
      - OUT035
      - OUT045
      - OUT046
      - OUT049  

    Outlet_Location_Type:
      - Tier 1
      - Tier 2
      - Tier 3
    
    Outlet_Type:
      - Grocery Store
      - Supermarket Type1
      - Supermarket Type2
      - Supermarket Type3
      


   