from Store_Sales.components.data_ingestion import DataIngestion
from Store_Sales.components.data_validation import DataValidation
from Store_Sales.components.data_cleaning import DataCleaning
from Store_Sales.components.data_transformation import DataTransformation
from Store_Sales.components.model_training import ModelTraining
from Store_Sales.components.model_evaluation import ModelEvaluation
from Store_Sales.components.model_pusher import ModelPusher